### Registrar pedido

GET https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/1029


POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/marca/1001/nuevo
Content-Type: application/json

{
 "nombre":"Kevin",
"descripcion": "Kevin Chambilla Gonzales",
	"precio":600,
	"stock":3
}